from __future__ import annotations

CITY_TO_DISTRICT = {
    "Pune": "Pune",
    "Pimpri": "Pune",
    "Chinchwad": "Pune",
    "Akurdi": "Pune",
    "Hadapsar": "Pune",
    "Wagholi": "Pune",
    "Talegaon": "Pune",
    "Ambegaon": "Pune",
    "Kondhwa": "Pune",
    "Bibwewadi": "Pune",
    "Shivajinagar": "Pune",
    "Karvenagar": "Pune",
    "Bavdhan": "Pune",
    "Baner": "Pune",
    "Lohegaon": "Pune",
    "Tathawade": "Pune",
    "Ravet": "Pune",
    "Hinjewadi": "Pune",
    "Alandi": "Pune",
    "Lonavala": "Pune",
    "Solapur": "Solapur",
    "Baramati": "Pune",
    "Nashik": "Nashik",
    "Dhule": "Dhule",
    "Jalgaon": "Jalgaon",
    "Nandurbar": "Nandurbar",
    "Ahmednagar": "Ahmednagar",
    "Sangamner": "Ahmednagar",
    "Anjaneri": "Nashik",
    "Trimbakeshwar": "Nashik",
    "Aurangabad": "Chhatrapati Sambhajinagar",
    "Chhatrapati Sambhajinagar": "Chhatrapati Sambhajinagar",
    "Jalna": "Jalna",
    "Beed": "Beed",
    "Latur": "Latur",
    "Osmanabad": "Dharashiv",
    "Dharashiv": "Dharashiv",
    "Nanded": "Nanded",
    "Hingoli": "Hingoli",
    "Parbhani": "Parbhani",
    "Ambejogai": "Beed",
    "Amravati": "Amravati",
    "Yavatmal": "Yavatmal",
    "Akola": "Akola",
    "Washim": "Washim",
    "Buldhana": "Buldhana",
    "Shegaon": "Buldhana",
    "Pusad": "Yavatmal",
    "Nagpur": "Nagpur",
    "Wardha": "Wardha",
    "Bhandara": "Bhandara",
    "Gondiya": "Gondiya",
    "Gadchiroli": "Gadchiroli",
    "Chandrapur": "Chandrapur",
    "Bhadrawati": "Chandrapur",
    "Arvi": "Wardha",
    "Mumbai": "Mumbai",
    "Thane": "Thane",
    "Navi Mumbai": "Thane",
    "Airoli": "Thane",
    "Kalyan": "Thane",
    "Dombivali": "Thane",
    "Panvel": "Raigad",
    "Ratnagiri": "Ratnagiri",
    "Sindhudurg": "Sindhudurg",
    "Byculla": "Mumbai",
    "Andheri": "Mumbai",
    "Chembur": "Mumbai",
    "Bandra": "Mumbai",
    "Kolhapur": "Kolhapur",
    "Sangli": "Sangli",
    "Satara": "Satara",
    "Gadhinglaj": "Kolhapur",
    "Budhgaon": "Sangli",
    "Ashta": "Sangli",
    "Miraj": "Sangli",
}


def get_district(city: str) -> str:
    city = city.strip()
    if not city:
        return ""

    for key, district in CITY_TO_DISTRICT.items():
        if key.lower() in city.lower():
            return district
    return city
